name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
        docker build -t my-backend:latest -f Dockerfile .

    - name: Save Docker image to a tar file
      run: |
        docker save my-backend:latest -o my-backend.tar
    
    - name: Copy Docker image to VM and load it
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USERNAME }}
        key: ${{ secrets.VM_SSH_KEY }}
        script: |
          scp -i ${{ secrets.VM_SSH_KEY }} -o StrictHostKeyChecking=no my-backend.tar ${{ secrets.VM_USERNAME }}@${{ secrets.VM_HOST }}:${{ secrets.VM_USERNAME }}/my-backend.tar
          ssh -i ${{ secrets.VM_SSH_KEY }} -o StrictHostKeyChecking=no ${{ secrets.VM_USERNAME }}@${{ secrets.VM_HOST }} "
            docker load -i /home/${{ secrets.VM_USERNAME }}/my-backend.tar &&
            rm /home/${{ secrets.VM_USERNAME }}/my-backend.tar &&
            docker run -d --name my-backend-container -p 80:80 my-backend:latest"